-- ============================================================
--  GRANJA AVÍCOLA - Dados de Teste
-- ============================================================

INSERT INTO TAB_LOTE_AVES (ID_LOTE, DESCRICAO, DATA_ENTRADA, QUANTIDADE_INICIAL)
VALUES (SEQ_LOTE_AVES.NEXTVAL, 'Lote Frango Corte - Galpão A', DATE '2026-01-10', 5000);

INSERT INTO TAB_LOTE_AVES (ID_LOTE, DESCRICAO, DATA_ENTRADA, QUANTIDADE_INICIAL)
VALUES (SEQ_LOTE_AVES.NEXTVAL, 'Lote Frango Corte - Galpão B', DATE '2026-01-15', 3000);

INSERT INTO TAB_LOTE_AVES (ID_LOTE, DESCRICAO, DATA_ENTRADA, QUANTIDADE_INICIAL)
VALUES (SEQ_LOTE_AVES.NEXTVAL, 'Lote Postura - Galpão C',      DATE '2026-02-01', 2000);

COMMIT;
